[build]
  command = "npm run build"
  publish = "build"
  # base = "" # Deja esto vacío o coméntalo si tu proyecto está en la raíz del repo

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200